version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - allow:
      - dependency-type: all
    directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly
    versioning-strategy: increase
  - directory: /.github/actions/set-up-python-environment/
    package-ecosystem: github-actions
    schedule:
      interval: weekly
