- hosts: pisco
  remote_user: pi
  collections:

    - ansible.builtin

  vars_prompt:

    - name: sonos_device_name
      default: Schlafzimmer
      prompt: What is the name of your Sonos device?
      private: no

  tasks:

    - name: Upgrade packages
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install packages
      become: yes
      apt:
        install_recommends: no
        name:
          - brightness-udev # allows unprivileged users to set brightness
          - git
          - libopenjp2-7    # required by Python package Pillow
          - lightdm
          - python3-pip
          - python3-tk
          - xserver-xorg

    - name: Set default locale
      become: yes
      command: raspi-config nonint do_change_locale en_US.UTF-8

    - name: Download setup script for display
      become: yes
      git:
        dest: /opt/github.com/pimoroni/hyperpixel4/
        repo: https://github.com/pimoroni/hyperpixel4.git
        version: square
    - name: Set up display
      become: yes
      command:
        chdir: /opt/github.com/pimoroni/hyperpixel4/
        cmd: ./install.sh
    - name: Set display rotation to 180°
      become: yes
      lineinfile:
        line: display_rotate=2
        path: /boot/config.txt
        regexp: '^display_rotate='
    - name: Disable screen blanking
      become: yes
      command: raspi-config nonint do_blanking 1

    - name: Enable autologin to GUI
      become: yes
      command: raspi-config nonint do_boot_behaviour B4
    - name: Fix auto-re-login
      become: yes
      copy:
        dest: /etc/lightdm/
        src: etc/lightdm/lightdm.conf.d

    - name: Install Pisco package
      become: yes
      pip:
        executable: pip3
        name: pisco
    - name: Start Pisco after login
      template:
        dest: /home/pi/.xsession
        src: home/pi/.xsession.j2

    - name: Reboot
      become: yes
      reboot: { }
