- hosts: pisco
  remote_user: pi
  collections:

    - ansible.builtin

  vars_prompt:

    - name: sonos_device_name
      default: Schlafzimmer
      prompt: What is the name of your Sonos device?
      private: false

  tasks:

    - name: Set default locale
      become: true
      command: raspi-config nonint do_change_locale en_US.UTF-8

    - name: Upgrade packages
      become: true
      apt:
        update_cache: true
        upgrade: true
    - name: Install packages
      become: true
      apt:
        install_recommends: false
        name:
          - brightness-udev # allows unprivileged users to set brightness
          - git
          - libopenjp2-7    # required by Python package Pillow
          - lightdm
          - python3-lxml    # required by Python package lxml (a dependency of soco)
          - python3-pip
          - python3-tk
          - python3-virtualenv
          - xserver-xorg

    - name: Download setup script for display
      become: true
      git:
        dest: /opt/github.com/pimoroni/hyperpixel4/
        repo: https://github.com/pimoroni/hyperpixel4.git
        version: square
    - name: Set up display
      become: true
      command:
        chdir: /opt/github.com/pimoroni/hyperpixel4/
        cmd: ./install.sh
    - name: Disable DRM VC4 V3D driver
      # cf. https://github.com/pimoroni/hyperpixel4/issues/177#issuecomment-1182557545
      become: true
      lineinfile:
        line: "# dtoverlay=vc4-kms-v3d"
        path: /boot/config.txt
        regexp: ^dtoverlay=vc4-kms-v3d
    - name: Set display rotation to 180°
      become: true
      lineinfile:
        line: display_rotate=2
        path: /boot/config.txt
        regexp: ^display_rotate=
    - name: Disable screen blanking
      become: true
      command: raspi-config nonint do_blanking 1

    - name: Enable autologin to GUI
      become: true
      command: raspi-config nonint do_boot_behaviour B4
    - name: Fix auto-re-login
      become: true
      copy:
        dest: /etc/lightdm/
        src: etc/lightdm/lightdm.conf.d

    - name: Install Pisco package
      become: true
      pip:
        name: pisco
        state: latest
        virtualenv: /opt/pisco/
    - name: Start Pisco after login
      template:
        dest: /home/pi/.xsession
        src: home/pi/.xsession.j2

    - name: Reboot
      become: true
      reboot: { }
