from typing_extensions import Never

from .music_library import MusicLibrary
from .services import AVTransport

class _ArgsSingleton(type):
    def __call__(cls, *args: Never, **kwargs: Never) -> object: ...

class _SocoSingletonBase(metaclass=_ArgsSingleton): ...

class SoCo(_SocoSingletonBase):
    avTransport: AVTransport
    music_library: MusicLibrary

    def __init__(self, ip_address: str) -> None: ...
    @property
    def player_name(self) -> str: ...
    def set_relative_volume(self, relative_volume: int) -> int: ...
    def play(self) -> None: ...
    def play_uri(
        self,
        uri: str = ...,
        meta: str = ...,
        title: str = ...,
        start: bool = ...,
        force_radio: bool = ...,
    ) -> bool | None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def next(self) -> None: ...
    def previous(self) -> None: ...
    @property
    def mute(self) -> bool: ...
    @mute.setter
    def mute(self, mute: bool) -> None: ...
    def get_current_transport_info(self) -> dict[str, object]: ...
