name: Set up Python environment
description: Install Python and poetry and, if desired, dependencies
inputs:
  install-dependencies:
    default: "false"
    description: whether to install the dependencies specified in pyproject.toml
    required: true
  poetry-version:
    default: 1.7.1
    description: poetry version to be installed
    required: true
  python-version:
    default: "3.9"
    description: Python version to be installed
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: ${{ inputs.poetry-version }}
    - if: fromJSON(inputs.install-dependencies)
      run: poetry install
      shell: bash
