name: CI

on:
  - push

permissions: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/set-up-python-environment
      - if: github.ref_type == 'tag'
        run: poetry version $(git describe --tags --abbrev=0)
      - run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: package-files
          path: |
            dist/
            pyproject.toml
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/set-up-python-environment
        with:
          install-dependencies: true
          python-version: ${{ matrix.python-version }}
      - run: poetry run pre-commit run --all-files --show-diff-on-failure
  publish:
    if: github.ref_type == 'tag'
    needs:
      - build
      - lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          name: package-files
      - uses: ./.github/actions/set-up-python-environment
      - env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_token }}
        run: poetry publish
