name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - if: github.ref_type == 'tag'
        run: poetry version $(git describe --tags --abbrev=0)
      - run: poetry build
      - uses: actions/upload-artifact@v2
        with:
          name: configuration
          path: pyproject.toml
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - run: poetry install
      - run: poetry run pre-commit run --all-files
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
          - windows-2022
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - run: poetry install
      - run: poetry run pytest --cov=src --cov-report term-missing
  type_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - run: poetry install
      - run: poetry run mypy . --platform darwin --python-version 3.7
      - run: poetry run mypy . --platform darwin --python-version 3.8
      - run: poetry run mypy . --platform darwin --python-version 3.9
      - run: poetry run mypy . --platform darwin --python-version 3.10
      - run: poetry run mypy . --platform linux --python-version 3.7
      - run: poetry run mypy . --platform linux --python-version 3.8
      - run: poetry run mypy . --platform linux --python-version 3.9
      - run: poetry run mypy . --platform linux --python-version 3.10
      - run: poetry run mypy . --platform win32 --python-version 3.7
      - run: poetry run mypy . --platform win32 --python-version 3.8
      - run: poetry run mypy . --platform win32 --python-version 3.9
      - run: poetry run mypy . --platform win32 --python-version 3.10
  publish:
    if: github.ref_type == 'tag'
    needs:
      - build
      - lint
      - test
      - type_check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: configuration
      - uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - run: poetry publish
