name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-python-environment
      - if: github.ref_type == 'tag'
        run: poetry version $(git describe --tags --abbrev=0)
      - run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: package-files
          path: |
            dist/
            pyproject.toml
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-python-environment
        with:
          install-dependencies: true
      - run: poetry run pre-commit run --all-files
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - ubuntu-22.04
          - windows-2022
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          # - "3.11"  # "poetry install" fails when combined with windows-2022 (as of October 2022)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-python-environment
        with:
          install-dependencies: true
          python-version: ${{ matrix.python-version }}
      - run: poetry run pytest --cov=src --cov-report term-missing
  type_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-up-python-environment
        with:
          install-dependencies: true
      - run: poetry run mypy . --platform darwin --python-version 3.7
      - run: poetry run mypy . --platform darwin --python-version 3.8
      - run: poetry run mypy . --platform darwin --python-version 3.9
      - run: poetry run mypy . --platform darwin --python-version 3.10
      - run: poetry run mypy . --platform darwin --python-version 3.11
      - run: poetry run mypy . --platform linux --python-version 3.7
      - run: poetry run mypy . --platform linux --python-version 3.8
      - run: poetry run mypy . --platform linux --python-version 3.9
      - run: poetry run mypy . --platform linux --python-version 3.10
      - run: poetry run mypy . --platform linux --python-version 3.11
      - run: poetry run mypy . --platform win32 --python-version 3.7
      - run: poetry run mypy . --platform win32 --python-version 3.8
      - run: poetry run mypy . --platform win32 --python-version 3.9
      - run: poetry run mypy . --platform win32 --python-version 3.10
      - run: poetry run mypy . --platform win32 --python-version 3.11
  publish:
    if: github.ref_type == 'tag'
    needs:
      - build
      - lint
      - test
      - type_check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: package-files
      - uses: ./.github/actions/set-up-python-environment
      - env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_token }}
        run: poetry publish
