name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - run: poetry install
      - run: poetry run pre-commit run --all-files
      - run: poetry run mypy .
      - run: poetry run pytest --cov=src --cov-report term-missing
      - run: poetry build
